### ISSUE TITLE
Vant4 文档移除这个，应该是支持自动导入样式了？!

### ISSUE THREAD

**Issue by M69W** [980320/h5-template#1]
https://github.com/980320/h5-template/blob/5ffbf7a242d3fa382aef07ab83357c3ac80572b8/src/utils/vant.ts#L3

https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart#fang-fa-er.-an-xu-yin-ru-zu-jian-yang-shi

```
"@vant/auto-import-resolver": "^1.1.0",

"unplugin-auto-import": "^0.17.5",
"unplugin-vue-components": "^0.26.0",
```

**Comment by wangchaoxx** [comment]
![image](https://github.com/980320/h5-template/assets/42869522/ec04dee3-ddfb-4a7d-80cc-2de6c39a71db)
我看更新日志最新版本应该是可以了吧，我用 4.8.5 版本的不会自动引入

**Comment by M69W** [comment]
https://github.com/980320/h5-template/blob/main/vite.config.ts#L17-L28


https://github.com/youzan/vant/blob/main/packages/vant-auto-import-resolver/README.md#vite

https://github.com/youzan/vant/commit/66d8a1800c196aa2554d6ea0b458f9ec84c1f27d

package.json
```
"@vant/auto-import-resolver": "^1.1.0",

"unplugin-auto-import": "^0.17.5",
"unplugin-vue-components": "^0.26.0",
```

vite.config.js
```
import AutoImport from "unplugin-auto-import/vite";
import Components from "unplugin-vue-components/vite";
import { VantResolver } from "@vant/auto-import-resolver";

AutoImport({
  resolvers: [VantResolver()]
}),
Components({
  resolvers: [VantResolver()]
}),
```
